site_name: XDforensics-Wiki
extra:
  search:
    language: 'jp'
nav:
    - About: index.md
    - Laws and Regulations : law.md
    - Preparation: preparation.md
    - RAM Analysis : ram.md
    - Windows: win.md
    - Linux : linux.md
    - MacOS : mac.md
    - Mobile Devices : mobile.md
    - Packet Analysis : pac.md
theme:
  name: 'material'
  feature:
    tabs: true
  language: 'zh'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde